numberfield added with error labeling
heusalagroup/fi.hg.frontend pull request #1
Opened 2022-07-26 12:52 UTC by EVCareeria

2022-07-26 13:09 UTC, thejhh requested changes
More refactoring required and possibly some design

2022-07-26 13:09 UTC, thejhh commented on components/fields/number/NumberField.tsx
> +    const onChangeHandler = (event:any) =>  {
This should use `useCallback`. 

Also, move it as a new reusable custom hook instead under the [`hooks/fields/number`](https://github.com/heusalagroup/fi.hg.frontend/tree/main/hooks/field/number).

2022-07-26 13:09 UTC, thejhh commented on components/fields/number/NumberField.tsx
> +        onChangeCallback
We probably should have `useIntegerField` instead, that gives `onChangeCallback()` that's optimized for it, and this normal would give the callback below.

2022-07-26 13:09 UTC, thejhh commented on components/fields/number/NumberField.tsx
> +        toNumber(decimalValue) // returns false if decimal
Hmm, where does it return it? Not from this function...

2022-07-26 13:09 UTC, thejhh commented on components/fields/number/NumberField.tsx
> +    const [decimalValue, setDecimalValue] = useState<string>('');
We should have `useIntegerField()` and `useNumberField()` and these states should be implemented inside `useNumberField()`.

However, I'm not yet sure if this implementation is very good... However, it anyway should be done inside a specialized hook (and that hook may or may not use different other hooks to implement it's logic.) It probably looks clearer how it should be done, once done so.

2022-07-26 13:09 UTC, thejhh commented on components/fields/number/NumberField.tsx
> +function toNumber (value : string | undefined) : number | undefined {
These functions should be inside a reusable hook and/or Utils class.

2022-08-02 15:54 UTC, EVCareeria commented
Managed to get the component working in-sync 'Had to call change(toNumber())) twice however', error style only turns text red however. Tested in proc. app

2022-08-08 08:20 UTC, closed without merging